version: 2

before:
  hooks:
    - npm ci

projects:
  backend:
    directory: ./backend
  frontend:
    directory: ./frontend

build:
  os: ubuntu-22.04
  tools:
    nodejs: "18"

python:
  version: 3.8

formats:
  - openapi
  - asyncapi

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 70%

github_checks:
  annotations: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
